CREATE TABLE [dbo].[PollOption]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[OptionText] NVARCHAR(200) NOT NULL,
	[PollId] INT NOT NULL
	CONSTRAINT [FK_PollOption_Poll] FOREIGN KEY (PollId) REFERENCES [Poll]([Id]),
)
